# Generated by Django 2.2 on 2020-03-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(max_length=100)),
                ('Manufacturer', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('PurchaseDate', models.DateField()),
                ('Supplier', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
